version: '3'

services:
  frontend:
    build: react
    image: react-frontend
    container_name: frontend
    networks:
      - sub-ethx
  backend:
    build: flask
    image: flask-backend
    container_name: backend
    networks:
      - sub-ethx
    ports:
      - "9090:9090"     
  revproxy:
    build: nginx
    image: reverse-proxy
    container_name: revproxy
    networks:
      - sub-ethx
    ports:
      - "80:80"
networks:
    sub-ethx:



 