# test remove reverse proxy
version: '3'

services:
  frontend:
    build: react
    image: react-frontend
    container_name: frontend
    networks:
      - sub-ethx
    ports:
      - "80:80"  
  backend:
    build: flask
    image: flask-backend
    container_name: backend
    networks:
      - sub-ethx
    ports:
      - "9090:9090"     
networks:
    sub-ethx:



 