name: Deploy to Container Registry

on:
  push:
    branches: [ feature/kubernetes ]
    paths: .github/workflows/build.yml
  pull_request:
    branches:  none # [ main ]
  workflow_dispatch:

jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: projectdharma
      IMAGE_NAME1: flask-appx
      IMAGE_NAME2: react-appx
      IMAGE_NAME3: nginx-appx
      IMAGE_TAG: ${{ github.run_number }} 
          
    steps:

    - name: Git Checkout
      uses: actions/checkout@v2
  
    - name: Build Docker Image Flask
      run:
        docker build ./flask/ --file ./flask/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME1:$GITHUB_RUN_NUMBER  --no-cache
    
    - name: Build Docker Image NGINX
      run:
        docker build ./nginx/ --file ./nginx/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME2:$GITHUB_RUN_NUMBER  --no-cache

    - name: Build Docker Image React
      run:
        docker build ./react/ --file ./react/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME3:$GITHUB_RUN_NUMBER  --no-cache

    - name: Login to Docker Hub
      run: |
        docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_PASS }} 
  
    - name: Push Flask Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME1:$GITHUB_RUN_NUMBER
    
    - name: Push NGINX image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME2:$GITHUB_RUN_NUMBER
    
    - name: Push React Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME3:$GITHUB_RUN_NUMBER
